/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "G:\\tutorials\\web3ApprenticeTutorials\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-fee1ad68",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fee1ad68").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-fc060cc0",
    path: "/web3modal-vue-tutorial/Contents.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fc060cc0").then(next)
    },
  },
  {
    name: "v-a23fe400",
    path: "/web3modal-vue-tutorial/Main.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a23fe400").then(next)
    },
  },
  {
    name: "v-799d5920",
    path: "/web3modal-vue-tutorial/NPCs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-799d5920").then(next)
    },
  },
  {
    name: "v-53a82396",
    path: "/web3modal-vue-tutorial/Mercenary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53a82396").then(next)
    },
  },
  {
    name: "v-573d9234",
    path: "/web3modal-vue-tutorial/OfficialLinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-573d9234").then(next)
    },
  },
  {
    name: "v-ee084a1c",
    path: "/web3modal-vue-tutorial/PlotRenting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ee084a1c").then(next)
    },
  },
  {
    name: "v-39e8b6c0",
    path: "/web3modal-vue-tutorial/Project_Timeline.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39e8b6c0").then(next)
    },
  },
  {
    name: "v-f3d520d4",
    path: "/web3modal-vue-tutorial/PlotStaking.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f3d520d4").then(next)
    },
  },
  {
    name: "v-85510128",
    path: "/web3modal-vue-tutorial/Related.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-85510128").then(next)
    },
  },
  {
    name: "v-409d469e",
    path: "/web3modal-vue-tutorial/Plots.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-409d469e").then(next)
    },
  },
  {
    name: "v-6793ac62",
    path: "/web3modal-vue-tutorial/Staking_Battle_Pass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6793ac62").then(next)
    },
  },
  {
    name: "v-29238dab",
    path: "/web3modal-vue-tutorial/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29238dab").then(next)
    },
  },
  {
    path: "/web3modal-vue-tutorial/index.html",
    redirect: "/web3modal-vue-tutorial/"
  },
  {
    name: "v-b0dec084",
    path: "/web3modal-vue-tutorial/Renting_Battle_Pass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b0dec084").then(next)
    },
  },
  {
    name: "v-8a5b5b58",
    path: "/web3modal-vue-tutorial/ServerDocumentation.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8a5b5b58").then(next)
    },
  },
  {
    name: "v-51b67f50",
    path: "/web3modal-vue-tutorial/TheVision.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51b67f50").then(next)
    },
  },
  {
    name: "v-5804a984",
    path: "/web3modal-vue-tutorial/welcome.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5804a984").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]