/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "Official Documentation Site for the BlockForge NFT Project",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Forge Token - BlockForge Documentation",
      "frontmatter": {
        "title": "Forge Token - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/ForgeToken.html",
      "relativePath": "blockforge/ForgeToken.md",
      "key": "v-778b0ae8",
      "path": "/blockforge/ForgeToken.html",
      "headers": [
        {
          "level": 3,
          "title": "Introduction",
          "slug": "introduction"
        },
        {
          "level": 2,
          "title": "Why Earn $FORGE ?",
          "slug": "why-earn-forge"
        },
        {
          "level": 3,
          "title": "Claim Plots",
          "slug": "claim-plots"
        },
        {
          "level": 3,
          "title": "Block Fortifications",
          "slug": "block-fortifications"
        },
        {
          "level": 3,
          "title": "Arenas",
          "slug": "arenas"
        },
        {
          "level": 2,
          "title": "Tokenomics & Distribution",
          "slug": "tokenomics-distribution"
        },
        {
          "level": 2,
          "title": "Claim Forge Tokens",
          "slug": "claim-forge-tokens"
        }
      ]
    },
    {
      "title": "Arenas - BlockForge Documentation",
      "frontmatter": {
        "title": "Arenas - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/Arenas.html",
      "relativePath": "blockforge/Arenas.md",
      "key": "v-c8b3afb0",
      "path": "/blockforge/Arenas.html",
      "headers": [
        {
          "level": 2,
          "title": "Resource Arena",
          "slug": "resource-arena"
        },
        {
          "level": 2,
          "title": "Duel Arena",
          "slug": "duel-arena"
        },
        {
          "level": 2,
          "title": "Quest Arena",
          "slug": "quest-arena"
        }
      ]
    },
    {
      "title": "Battle Mode - BlockForge Documentation",
      "frontmatter": {
        "title": "Battle Mode - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/Battle_Mode.html",
      "relativePath": "blockforge/Battle_Mode.md",
      "key": "v-04ba1e6c",
      "path": "/blockforge/Battle_Mode.html",
      "headers": [
        {
          "level": 2,
          "title": "Introduction",
          "slug": "introduction"
        },
        {
          "level": 2,
          "title": "Requirements",
          "slug": "requirements"
        },
        {
          "level": 2,
          "title": "Plot Rank",
          "slug": "plot-rank"
        },
        {
          "level": 3,
          "title": "Equation",
          "slug": "equation"
        }
      ]
    },
    {
      "title": "DOTD - BlockForge Documentation",
      "frontmatter": {
        "title": "DOTD - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/DefenseOfTheDiamonds.html",
      "relativePath": "blockforge/DefenseOfTheDiamonds.md",
      "key": "v-39b14288",
      "path": "/blockforge/DefenseOfTheDiamonds.html",
      "headers": [
        {
          "level": 2,
          "title": "Raiding",
          "slug": "raiding"
        },
        {
          "level": 2,
          "title": "Block Fortification",
          "slug": "block-fortification"
        },
        {
          "level": 3,
          "title": "Block Break Time",
          "slug": "block-break-time"
        },
        {
          "level": 3,
          "title": "Redeeming Defensive Blocks",
          "slug": "redeeming-defensive-blocks"
        }
      ]
    },
    {
      "title": "Links - BlockForge Documentation",
      "frontmatter": {
        "title": "Links - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/OfficialLinks.html",
      "relativePath": "blockforge/OfficialLinks.md",
      "key": "v-3eff857c",
      "path": "/blockforge/OfficialLinks.html",
      "headers": [
        {
          "level": 2,
          "title": "Common Links",
          "slug": "common-links"
        },
        {
          "level": 2,
          "title": "Token Links",
          "slug": "token-links"
        },
        {
          "level": 2,
          "title": "Battle Pass Links",
          "slug": "battle-pass-links"
        },
        {
          "level": 2,
          "title": "Plot Links",
          "slug": "plot-links"
        }
      ]
    },
    {
      "title": "Mercenary - BlockForge Documentation",
      "frontmatter": {
        "title": "Mercenary - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/Mercenary.html",
      "relativePath": "blockforge/Mercenary.md",
      "key": "v-2cde161c",
      "path": "/blockforge/Mercenary.html",
      "headers": [
        {
          "level": 2,
          "title": "Defending",
          "slug": "defending"
        },
        {
          "level": 2,
          "title": "Plot Owner Bounty",
          "slug": "plot-owner-bounty"
        }
      ]
    },
    {
      "title": "NPCs - BlockForge Documentation",
      "frontmatter": {
        "title": "NPCs - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/NPCs.html",
      "relativePath": "blockforge/NPCs.md",
      "key": "v-5e5af1b0",
      "path": "/blockforge/NPCs.html",
      "headers": [
        {
          "level": 2,
          "title": "BlockForge Spawn",
          "slug": "blockforge-spawn"
        }
      ]
    },
    {
      "title": "Renting Plots - BlockForge Documentation",
      "frontmatter": {
        "title": "Renting Plots - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/PlotRenting.html",
      "relativePath": "blockforge/PlotRenting.md",
      "key": "v-6dc04dce",
      "path": "/blockforge/PlotRenting.html",
      "headers": [
        {
          "level": 2,
          "title": "Utility of a Rented Plot",
          "slug": "utility-of-a-rented-plot"
        },
        {
          "level": 2,
          "title": "Minimum Renting Duration",
          "slug": "minimum-renting-duration"
        }
      ]
    },
    {
      "title": "Roadmap - BlockForge Documentation",
      "frontmatter": {
        "title": "Roadmap - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/Project_Timeline.html",
      "relativePath": "blockforge/Project_Timeline.md",
      "key": "v-6a3a7570",
      "path": "/blockforge/Project_Timeline.html"
    },
    {
      "title": "Staking Plots - BlockForge Documentation",
      "frontmatter": {
        "title": "Staking Plots - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/PlotStaking.html",
      "relativePath": "blockforge/PlotStaking.md",
      "key": "v-d7eda51c",
      "path": "/blockforge/PlotStaking.html",
      "headers": [
        {
          "level": 2,
          "title": "How to Stake",
          "slug": "how-to-stake"
        },
        {
          "level": 2,
          "title": "How to Unstake",
          "slug": "how-to-unstake"
        }
      ]
    },
    {
      "title": "Plot NFT - BlockForge Documentation",
      "frontmatter": {
        "title": "Plot NFT - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/Plots.html",
      "relativePath": "blockforge/Plots.md",
      "key": "v-1dd0c4fa",
      "path": "/blockforge/Plots.html",
      "headers": [
        {
          "level": 2,
          "title": "Plot Of Land",
          "slug": "plot-of-land"
        },
        {
          "level": 2,
          "title": "Utility",
          "slug": "utility"
        },
        {
          "level": 2,
          "title": "Token Generation",
          "slug": "token-generation"
        },
        {
          "level": 3,
          "title": "Calulation",
          "slug": "calulation"
        },
        {
          "level": 2,
          "title": "Claim Plots",
          "slug": "claim-plots"
        },
        {
          "level": 3,
          "title": "Plot Price Calculation",
          "slug": "plot-price-calculation"
        }
      ]
    },
    {
      "title": "Foreward",
      "frontmatter": {
        "title": "Foreward",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/",
      "relativePath": "blockforge/README.md",
      "key": "v-32a84dba",
      "path": "/blockforge/"
    },
    {
      "title": "Renting Battle Pass - BlockForge Documentation",
      "frontmatter": {
        "title": "Renting Battle Pass - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/Renting_Battle_Pass.html",
      "relativePath": "blockforge/Renting_Battle_Pass.md",
      "key": "v-51d4e4cc",
      "path": "/blockforge/Renting_Battle_Pass.html",
      "headers": [
        {
          "level": 2,
          "title": "Utility of a Rented Battle Pass",
          "slug": "utility-of-a-rented-battle-pass"
        },
        {
          "level": 2,
          "title": "Minimum Renting Duration",
          "slug": "minimum-renting-duration"
        }
      ]
    },
    {
      "title": "Staking Battle Pass - BlockForge Documentation",
      "frontmatter": {
        "title": "Staking Battle Pass - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/Staking_Battle_Pass.html",
      "relativePath": "blockforge/Staking_Battle_Pass.md",
      "key": "v-22b4653e",
      "path": "/blockforge/Staking_Battle_Pass.html",
      "headers": [
        {
          "level": 2,
          "title": "Staked VS. Non-Staked Battle Pass",
          "slug": "staked-vs-non-staked-battle-pass"
        },
        {
          "level": 2,
          "title": "How to Stake",
          "slug": "how-to-stake"
        },
        {
          "level": 2,
          "title": "How to Unstake",
          "slug": "how-to-unstake"
        }
      ]
    },
    {
      "title": "The Vision for BlockForge",
      "frontmatter": {
        "title": "The Vision for BlockForge",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/TheVision.html",
      "relativePath": "blockforge/TheVision.md",
      "key": "v-5ba9942c",
      "path": "/blockforge/TheVision.html"
    },
    {
      "title": "Connect - BlockForge Documentation",
      "frontmatter": {
        "title": "Connect - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/ServerDocumentation.html",
      "relativePath": "blockforge/ServerDocumentation.md",
      "key": "v-e0a5aea0",
      "path": "/blockforge/ServerDocumentation.html",
      "headers": [
        {
          "level": 2,
          "title": "Download Minecraft",
          "slug": "download-minecraft"
        },
        {
          "level": 2,
          "title": "Connect to the Island of Karniel",
          "slug": "connect-to-the-island-of-karniel"
        },
        {
          "level": 2,
          "title": "Verify Your Wallet",
          "slug": "verify-your-wallet"
        }
      ]
    },
    {
      "title": "Foreward - BlockForge Documentation",
      "frontmatter": {
        "title": "Foreward - BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/welcome.html",
      "relativePath": "blockforge/welcome.md",
      "key": "v-c4c3e3cc",
      "path": "/blockforge/welcome.html"
    },
    {
      "title": "Battle Pass NFT- BlockForge Documentation",
      "frontmatter": {
        "title": "Battle Pass NFT- BlockForge Documentation",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/battle-pass.html",
      "relativePath": "blockforge/battle-pass.md",
      "key": "v-046d4052",
      "path": "/blockforge/battle-pass.html",
      "headers": [
        {
          "level": 2,
          "title": "Diamond Battle Pass",
          "slug": "diamond-battle-pass"
        },
        {
          "level": 2,
          "title": "Token Generation",
          "slug": "token-generation"
        },
        {
          "level": 3,
          "title": "Equation",
          "slug": "equation"
        },
        {
          "level": 2,
          "title": "Utility",
          "slug": "utility"
        },
        {
          "level": 2,
          "title": "Whitelist",
          "slug": "whitelist"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "pageClass": "custom-page-class",
        "actionText": "See All Documentation",
        "actionLink": "/blockforge/welcome",
        "heroImage": "/logo.png",
        "heroText": null,
        "features": [
          {
            "title": "WhitePaper",
            "details": "Information relating to the vision, concept and development of the BlockForge NFT Project"
          },
          {
            "title": "Server Documentation",
            "details": "Information related to the BlockForge MineCraft Server"
          },
          {
            "title": "GamePlay",
            "details": "Information related to the BlockForge GamePlay"
          }
        ],
        "footer": "The BlockForge Development Team is in no way affiliated with, endorsed by, or a partner of Minecraft, Mojang, Microsoft, or any other related parties."
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-bd5eb1d8",
      "path": "/"
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "nav": [
      {
        "text": "WhitePaper",
        "link": "/blockforge/"
      },
      {
        "text": "Gameplay Documentation",
        "link": "/blockforge/GameMechanics"
      },
      {
        "text": "Server Documentation",
        "link": "/blockforge/placeholder"
      }
    ],
    "sidebar": [
      {
        "title": "WhitePaper",
        "collapsable": false,
        "children": [
          [
            "/blockforge/welcome",
            "Foreward"
          ],
          [
            "/blockforge/Project_Timeline",
            "Project Roadmap"
          ],
          [
            "/blockforge/Battle_Mode",
            "Battle Mode"
          ],
          [
            "/blockforge/battle-pass",
            "Battle Pass NFT"
          ],
          [
            "/blockforge/Staking_Battle_Pass",
            "Staking Battle Passes"
          ],
          [
            "/blockforge/Renting_Battle_Pass",
            "Renting Battle Passes"
          ],
          [
            "/blockforge/Plots",
            "Plot NFT"
          ],
          [
            "/blockforge/PlotStaking",
            "Staking Plot NFTs"
          ],
          [
            "/blockforge/PlotRenting",
            "Renting Plot NFTs"
          ],
          [
            "/blockforge/ForgeToken",
            "$FORGE Token"
          ]
        ]
      },
      {
        "title": "GamePlay",
        "collapsable": false,
        "children": [
          [
            "/blockforge/DefenseOfTheDiamonds",
            "Defense Of The Diamonds"
          ],
          [
            "/blockforge/Arenas",
            "Arenas"
          ],
          [
            "/blockforge/Mercenary",
            "Play as a Mercenary"
          ],
          [
            "/blockforge/NPCs",
            "NPCs"
          ]
        ]
      },
      {
        "title": "Server Documentation",
        "collapsable": false,
        "children": [
          [
            "/blockforge/ServerDocumentation",
            "Connect to Server"
          ],
          [
            "/blockforge/OfficialLinks",
            "Official Links"
          ]
        ]
      }
    ]
  }
}