/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "Official Documentation Site for the BlockForge NFT Project",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Staking Plots",
      "frontmatter": {
        "title": "Staking Plots",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/PlotStaking.html",
      "relativePath": "blockforge/PlotStaking.md",
      "key": "v-680fa670",
      "path": "/blockforge/PlotStaking.html",
      "headers": [
        {
          "level": 2,
          "title": "Plot Vulnerability",
          "slug": "plot-vulnerability"
        }
      ]
    },
    {
      "title": "Purchasing Plots on the server",
      "frontmatter": {
        "title": "Purchasing Plots on the server",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/Plots.html",
      "relativePath": "blockforge/Plots.md",
      "key": "v-23739550",
      "path": "/blockforge/Plots.html"
    },
    {
      "title": "Project Scope",
      "frontmatter": {
        "title": "Project Scope",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/Project_Scope.html",
      "relativePath": "blockforge/Project_Scope.md",
      "key": "v-2010d598",
      "path": "/blockforge/Project_Scope.html"
    },
    {
      "title": "Staking for BlockForge Pass Holders",
      "frontmatter": {
        "title": "Staking for BlockForge Pass Holders",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/Staking_Battle_Pass.html",
      "relativePath": "blockforge/Staking_Battle_Pass.md",
      "key": "v-0bd5f894",
      "path": "/blockforge/Staking_Battle_Pass.html",
      "headers": [
        {
          "level": 2,
          "title": "Staking Rewards",
          "slug": "staking-rewards"
        },
        {
          "level": 2,
          "title": "Unstaking your BlockForge Battle Pass",
          "slug": "unstaking-your-blockforge-battle-pass"
        }
      ]
    },
    {
      "title": "Renting for BlockForge Pass Holders",
      "frontmatter": {
        "title": "Renting for BlockForge Pass Holders",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/Renting_Battle_Pass.html",
      "relativePath": "blockforge/Renting_Battle_Pass.md",
      "key": "v-7f91be20",
      "path": "/blockforge/Renting_Battle_Pass.html"
    },
    {
      "title": "Foreward",
      "frontmatter": {
        "title": "Foreward",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/",
      "relativePath": "blockforge/README.md",
      "key": "v-530b300d",
      "path": "/blockforge/"
    },
    {
      "title": "Foreward",
      "frontmatter": {
        "title": "Foreward",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/welcome.html",
      "relativePath": "blockforge/welcome.md",
      "key": "v-7a14c370",
      "path": "/blockforge/welcome.html"
    },
    {
      "title": "Placeholder text",
      "frontmatter": {
        "title": "Placeholder text",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/placeholder.html",
      "relativePath": "blockforge/placeholder.md",
      "key": "v-36c4f34e",
      "path": "/blockforge/placeholder.html",
      "headers": [
        {
          "level": 3,
          "title": "Placeholder Text",
          "slug": "placeholder-text"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "pageClass": "custom-page-class",
        "actionText": "See All Documentation",
        "actionLink": "/blockforge/",
        "heroImage": "/logo.png",
        "heroText": null,
        "features": [
          {
            "title": "WhitePaper",
            "details": "Information relating to the vision, concept and development of the BlockForge NFT Project"
          },
          {
            "title": "Server Documentation",
            "details": "Information related to the BlockForge MineCraft Server"
          },
          {
            "title": "GamePlay Documentation",
            "details": "Information related to the BlockForge GamePlay"
          }
        ],
        "footer": "The BlockForge Development Team is in no way affiliated with, endorsed by, or a partner of Minecraft, Mojang, Microsoft, or any other related parties."
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-311a4f6a",
      "path": "/"
    },
    {
      "title": "BlockForge Battle Pass",
      "frontmatter": {
        "title": "BlockForge Battle Pass",
        "pageClass": "content-page-class-general"
      },
      "regularPath": "/blockforge/battle-pass.html",
      "relativePath": "blockforge/battle-pass.md",
      "key": "v-3c5c3fa8",
      "path": "/blockforge/battle-pass.html",
      "headers": [
        {
          "level": 2,
          "title": "Pass Types & Rarity",
          "slug": "pass-types-rarity"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "nav": [
      {
        "text": "WhitePaper",
        "link": "/blockforge/"
      },
      {
        "text": "Server Documentation",
        "link": "/blockforge/placeholder"
      },
      {
        "text": "Gameplay Documentation",
        "link": "/blockforge/placeholder"
      }
    ],
    "sidebar": [
      {
        "title": "WhitePaper",
        "collapsable": false,
        "children": [
          [
            "/blockforge/welcome",
            "Foreward"
          ],
          [
            "/blockforge/Project_Scope",
            "Project Scope"
          ],
          [
            "/blockforge/battle-pass",
            "Battle Pass Token"
          ],
          [
            "/blockforge/Staking_Battle_Pass",
            "Staking Battle Pass"
          ],
          [
            "/blockforge/Renting_Battle_Pass",
            "Renting Battle Pass"
          ],
          [
            "/blockforge/Plots",
            "Purchasing Plots"
          ],
          [
            "/blockforge/PlotStaking",
            "Staking Plots"
          ]
        ]
      },
      {
        "title": "Server Documentation",
        "collapsable": false,
        "children": [
          [
            "/blockforge/placeholder",
            "Connect to Server"
          ]
        ]
      },
      {
        "title": "GamePlay",
        "collapsable": false,
        "children": [
          [
            "/blockforge/placeholder",
            "Game Mechanics"
          ]
        ]
      }
    ]
  }
}