/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "BlockForge NFT",
  "description": "Official Documentation Site for BlockForge NFT",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Purchasing Plots on the server",
      "frontmatter": {
        "title": "Purchasing Plots on the server"
      },
      "regularPath": "/blockforge/Plots.html",
      "relativePath": "blockforge/Plots.md",
      "key": "v-23739550",
      "path": "/blockforge/Plots.html"
    },
    {
      "title": "Foreward",
      "frontmatter": {
        "title": "Foreward"
      },
      "regularPath": "/blockforge/",
      "relativePath": "blockforge/README.md",
      "key": "v-530b300d",
      "path": "/blockforge/"
    },
    {
      "title": "Staking Plots",
      "frontmatter": {
        "title": "Staking Plots"
      },
      "regularPath": "/blockforge/PlotStaking.html",
      "relativePath": "blockforge/PlotStaking.md",
      "key": "v-680fa670",
      "path": "/blockforge/PlotStaking.html",
      "headers": [
        {
          "level": 2,
          "title": "Plot Vulnerability",
          "slug": "plot-vulnerability"
        }
      ]
    },
    {
      "title": "Renting for BlockForge Pass Holders",
      "frontmatter": {
        "title": "Renting for BlockForge Pass Holders"
      },
      "regularPath": "/blockforge/Renting_Battle_Pass.html",
      "relativePath": "blockforge/Renting_Battle_Pass.md",
      "key": "v-7f91be20",
      "path": "/blockforge/Renting_Battle_Pass.html"
    },
    {
      "title": "Project Scope",
      "frontmatter": {
        "title": "Project Scope"
      },
      "regularPath": "/blockforge/Project_Scope.html",
      "relativePath": "blockforge/Project_Scope.md",
      "key": "v-2010d598",
      "path": "/blockforge/Project_Scope.html"
    },
    {
      "title": "Staking for BlockForge Pass Holders",
      "frontmatter": {
        "title": "Staking for BlockForge Pass Holders"
      },
      "regularPath": "/blockforge/Staking_Battle_Pass.html",
      "relativePath": "blockforge/Staking_Battle_Pass.md",
      "key": "v-0bd5f894",
      "path": "/blockforge/Staking_Battle_Pass.html",
      "headers": [
        {
          "level": 2,
          "title": "Staking Rewards",
          "slug": "staking-rewards"
        },
        {
          "level": 2,
          "title": "Unstaking your BlockForge Battle Pass",
          "slug": "unstaking-your-blockforge-battle-pass"
        }
      ]
    },
    {
      "title": "Foreward",
      "frontmatter": {
        "title": "Foreward"
      },
      "regularPath": "/blockforge/welcome.html",
      "relativePath": "blockforge/welcome.md",
      "key": "v-7a14c370",
      "path": "/blockforge/welcome.html"
    },
    {
      "title": "BlockForge Battle Pass",
      "frontmatter": {
        "title": "BlockForge Battle Pass"
      },
      "regularPath": "/blockforge/battle-pass.html",
      "relativePath": "blockforge/battle-pass.md",
      "key": "v-3c5c3fa8",
      "path": "/blockforge/battle-pass.html",
      "headers": [
        {
          "level": 2,
          "title": "Pass Types & Rarity",
          "slug": "pass-types-rarity"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "See All Documentation",
        "actionLink": "/blockforge/",
        "heroImage": "/logo.png",
        "features": [
          {
            "title": "WhitePaper",
            "details": "Information relating to the vision, concept and development of the BlockForge NFT Project"
          },
          {
            "title": "Server Documentation",
            "details": "Information related to the BlockForge MineCraft Server"
          },
          {
            "title": "GamePlay Documentation",
            "details": "Information related to the BlockForge GamePlay"
          }
        ],
        "footer": "The BlockForge Development Team is in no way affiliated with, endorsed by, or a partner of Minecraft, Mojang, Microsoft, or any other related parties."
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-311a4f6a",
      "path": "/"
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "nav": [
      {
        "text": "BlockForge",
        "link": "/blockforge/"
      }
    ],
    "sidebar": [
      {
        "title": "Blockforge",
        "collapsable": false,
        "children": [
          [
            "/blockforge/welcome",
            "Foreward"
          ],
          [
            "/blockforge/battle-pass",
            "Battle Pass Token"
          ],
          [
            "/blockforge/Staking_Battle_Pass",
            "Staking Battle Pass"
          ],
          [
            "/blockforge/Renting_Battle_Pass",
            "Renting Battle Pass"
          ],
          [
            "/blockforge/Plots",
            "Purchasing Plots"
          ],
          [
            "/blockforge/PlotStaking",
            "Staking Plots"
          ]
        ]
      }
    ]
  }
}